-- ==========================================
-- 1. ENTITAS MASTER
-- ==========================================

-- Tabel 1: Kategori Bahan Baku
create table if not exists categories (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique
);

-- Tabel 2: Pemasok (Supplier) untuk audit barang masuk
create table if not exists suppliers (
    id bigint generated by default as identity primary key,
    name varchar(150) not null unique,
    phone varchar(20),
    address text
);

-- Tabel 3: Menu Pizza (Pemicu barang keluar & perhitungan HPP)
create table if not exists menu_items (
    id bigint generated by default as identity primary key,
    name varchar(150) not null unique,
    selling_price numeric(15,2) not null default 0
);

-- ==========================================
-- 2. ENTITAS PERSEDIAAN UTAMA
-- ==========================================

-- Tabel 4: Bahan Baku (Terhubung ke Kategori)
create table if not exists ingredients (
    id bigint generated by default as identity primary key,
    category_id bigint references categories(id) on delete set null,
    name varchar(150) not null unique,
    stock_qty numeric(12,2) not null default 0,
    unit varchar(20) not null, -- kg, liter, pcs
    min_stock numeric(12,2) not null default 0,
    unit_price numeric(15,2) not null default 0 -- Harga beli rata-rata per satuan (Rupiah)
);

-- Tabel 5: Jurnal Transaksi Persediaan / Kartu Stok
-- (Terhubung ke Bahan Baku, Supplier untuk barang IN, Menu untuk barang OUT)
create table if not exists inventory_logs (
    id bigint generated by default as identity primary key,
    ingredient_id bigint references ingredients(id) on delete cascade,
    supplier_id bigint references suppliers(id) on delete set null, -- Terisi jika type = 'IN'
    menu_item_id bigint references menu_items(id) on delete set null, -- Terisi jika type = 'OUT'
    
    type varchar(10) not null check (type in ('IN', 'OUT')),
    qty numeric(12,2) not null,
    
    -- Unsur Akuntansi: Nilai Rupiah dicatat mati di riwayat agar akurat
    unit_price_at_time numeric(15,2) not null, 
    total_value numeric(15,2) generated always as (qty * unit_price_at_time) stored,
    
    notes text,
    created_at timestamptz default now()
);

-- ==========================================
-- 3. KONFIGURASI KEAMANAN (KHUSUS DEVELOPMENT)
-- ==========================================
-- Matikan RLS agar Front-End (HTML/JS) bebas membaca/menulis data
alter table categories disable row level security;
alter table suppliers disable row level security;
alter table menu_items disable row level security;
alter table ingredients disable row level security;
alter table inventory_logs disable row level security;